routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return redirect('siswa_nilai');
});


Route::get('dataSiswa', function () {

    $dataSiswa = DB::table('siswa_nilai')->get();

    return view('siswa_nilai', ['siswa_nilai' => $dataSiswa]);
});

Route::get('/siswa_nilai/create', 'DataSiswaController@create');
Route::get('/siswa_nilai/{id}', 'DataSiswaController@show');
Route::post('/siswa_nilai/{id}/edit', 'DataSiswaController@edit');
Route::get('delete/{id}','DataSiswaController@destroy');

Route::resource('siswa_nilai','DataSiswaController');

app/DataSiswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class DataSiswa extends Model
{
	public $table = 'siswa_nilai';
	protected $primaryKey = 'id';

    protected $fillable = [
	'KD_PROP', 
	'KD_RAYO',
	'KD_SR',
	'KD_SEK',
	'NOPES',
	'NM_PES',
	'NISN',
	'SEX',
	'TMP_LHR',
	'TGL_LHR',
	'ALAMAT_1',
	'IND',
	'MAT',
	'IPA'
	];
	
	
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DataSiswaController.php
<?php

namespace App\Http\Controllers;

use App\DataSiswa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Quotation;

class DataSiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $siswa_nilai = DataSiswa::latest()->paginate(10);

        return view('siswa_nilai.index',compact('siswa_nilai'))
			   ->with('i', (request()->input('page', 1) - 1) * 10);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('siswa_nilai.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'KD_PROP' => 'required',
            'KD_RAYO' => 'required',
            'KD_SR' => 'required',
			'KD_SEK' => 'required',
			'NOPES' => 'required',
			'NM_PES' => 'required',
			'NISN' => 'required',
			'SEX' => 'required',
            'TMP_LHR' => 'required',
            'TGL_LHR' => 'required',
            'ALAMAT_1' => 'required',
            'IND' => 'required',
            'MAT' => 'required',
            'IPA' => 'required',
        ]);

  

        DataSiswa::create($request->all());

   

        return redirect()->route('siswa_nilai.index')
                         ->with('success','DataSiswa created successfully.');
	}

    /**
     * Display the specified resource.
     *
     * @param  \App\DataSiswa  $dataSiswa
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
		$siswa_nilai = DataSiswa::find($id);
		return view('siswa_nilai.show')
			   ->with('dataSiswa',$siswa_nilai);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\DataSiswa  $dataSiswa
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
		$siswa_nilai = DataSiswa::find($id);
		return view('siswa_nilai.edit')
			   ->with('dataSiswa',$siswa_nilai);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\DataSiswa  $dataSiswa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
		'KD_PROP' => 'required',
		'KD_RAYO' => 'required',
		'KD_SR' => 'required',
		'KD_SEK' => 'required',
		'NOPES' => 'required',
		'NM_PES' => 'required',
		'NISN' => 'required',
		'SEX' => 'required',
		'TMP_LHR' => 'required',
		'TGL_LHR' => 'required',
		'ALAMAT_1' => 'required',
		'IND' => 'required',
		'MAT' => 'required',
		'IPA' => 'required',
        ]);
        
	$siswa_nilai = DataSiswa::find($id);
	$siswa_nilai->update($request->all());

	return redirect()->route('siswa_nilai.index')
			->with('success','Data telah berhasil diperbaharui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\DataSiswa  $dataSiswa
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
		$siswa_nilai = DataSiswa::find($id);
        $siswa_nilai->delete($id);
        return redirect()->route('siswa_nilai.index')
                         ->with('success','Data telah berhasil dihapus');

    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                    
                    
                </div>
                
                
                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/siswa_nilai/create.blade.php
@extends('siswa_nilai.layout')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Data</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('siswa_nilai.index') }}"> Back</a>
        </div>
    </div>
</div>

   

@if ($errors->any())

    <div class="alert alert-danger">

        <strong>Whoops!</strong> There were some problems with your input.<br><br>

        <ul>

            @foreach ($errors->all() as $error)

                <li>{{ $error }}</li>

            @endforeach

        </ul>

    </div>

@endif

   

<form action="{{ route('siswa_nilai.store') }}" method="POST">

    {{ csrf_field() }}

     <div class="row">
	 <div class="col-xs-12 col-sm-12 col-md-12">
     <div class="form-group">
         <strong>Kode Propinsi:</strong>
         <input type="text" name="KD_PROP" class="form-control" placeholder="Kode Propinsi">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Kode Rayon:</strong>
         <input type="text" name="KD_RAYO" class="form-control" placeholder="Kode Rayon">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Kode SR:</strong>
         <input type="text" name="KD_SR" class="form-control" placeholder="Kode SR">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Kode Sekolah:</strong>
         <input type="text" name="KD_SEK" class="form-control" placeholder="Kode Sekolah">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Nomor Peserta:</strong>
         <input type="text" name="NOPES" class="form-control" placeholder="Nomor Peserta">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Nama Peserta:</strong>
         <input type="text" name="NM_PES" class="form-control" placeholder="Nama Peserta">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>NISN:</strong>
         <input type="text" name="NISN" class="form-control" placeholder="Nomo Induk Siswa Nasional">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Jenis Kelamin:</strong>
         <input type="text" name="SEX" class="form-control" placeholder="Jenis Kelamin">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Tempat Kelahiran:</strong>
         <input type="text" name="TMP_LHR" class="form-control" placeholder="Tempat Lahir">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Tanggal Lahir:</strong>
         <input type="text" name="TGL_LHR" class="form-control" placeholder="Tanggal Lahir">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>Alamat:</strong>
         <input type="text" name="ALAMAT_1" class="form-control" placeholder="Alamat">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>IND:</strong>
         <input type="text" name="IND" class="form-control" placeholder="Nilai Bahasa Indonesia">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>MAT:</strong>
         <input type="text" name="MAT" class="form-control" placeholder="Nilai Matematika">
      </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
         <strong>IPA:</strong>
         <input type="text" name="IPA" class="form-control" placeholder="Nilai IPA">
      </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

        </div>

    </div>

   

</form>

@endsection

resources/views/siswa_nilai/edit.blade.php
@extends('siswa_nilai.layout')

@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Edit Data</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('siswa_nilai.index') }}"> Back</a>

            </div>

        </div>

    </div>

   

    @if ($errors->any())

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif

  

    <form action="{{ route('siswa_nilai.update',$dataSiswa->id) }}" method="POST">

       <input type="hidden" name="_token" value="{{ csrf_token() }}">
		{{ csrf_field() }}
        {{ method_field('PUT') }}

   

         <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Kode Propinsi:</strong>
            <input type="text" name="KD_PROP" value="{{ $dataSiswa->KD_PROP }}" class="form-control" placeholder="Kode Propinsi">
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Kode Propinsi:</strong>
            <input type="text" name="KD_RAYO" value="{{ $dataSiswa->KD_RAYO }}" class="form-control" placeholder="Kode Rayon">
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Kode SR:</strong>
            <input type="text" name="KD_SR" value="{{ $dataSiswa->KD_SR }}" class="form-control" placeholder="Kode SR">
         </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Kode Sekolah:</strong>
            <input type="text" name="KD_SEK" value="{{ $dataSiswa->KD_SEK }}" class="form-control" placeholder="Kode Sekolah">
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Nomor Peserta:</strong>
            <input type="text" name="NOPES" value="{{ $dataSiswa->NOPES }}" class="form-control" placeholder="Nomor Peserta">
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Nama Peserta:</strong>
            <input type="text" name="NM_PES" value="{{ $dataSiswa->NM_PES }}" class="form-control" placeholder="Nama Peserta">
         </div>
      </div>
  
      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Nomor Induk:</strong>
            <input type="text" name="NISN" value="{{ $dataSiswa->NISN }}" class="form-control" placeholder="Nama Peserta">
         </div>
      </div>
 
      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Jenis Kelamin:</strong>
            <input type="text" name="SEX" value="{{ $dataSiswa->SEX }}" class="form-control" placeholder="Nama Peserta">
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Tempat Kelahiran:</strong>
            <input type="text" name="TMP_LHR" value="{{ $dataSiswa->TMP_LHR }}" class="form-control" placeholder="Tempat Lahir">
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Tanggal Lahir:</strong>
            <input type="text" name="TGL_LHR" value="{{ $dataSiswa->TGL_LHR }}" class="form-control" placeholder="Tanggal Lahir">
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Alamat:</strong>
            <input type="text" name="ALAMAT_1" value="{{ $dataSiswa->ALAMAT_1 }}" class="form-control" placeholder="Alamat">
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>IND:</strong>
            <input type="text" name="IND" value="{{ $dataSiswa->IND }}" class="form-control" placeholder="Nilai Bahasa Indonesia">
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>MAT:</strong>
            <input type="text" name="MAT" value="{{ $dataSiswa->MAT }}" class="form-control" placeholder="Nilai Matematika">
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>IPA:</strong>
            <input type="text" name="IPA" value="{{ $dataSiswa->IPA }}" class="form-control" placeholder="Nilai IPA">
         </div>
      </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">

              <button type="submit" class="btn btn-primary">Submit</button>

            </div>

        </div>

   

    </form>

@endsection

resources/views/siswa_nilai/index.blade.php
@extends('siswa_nilai.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
				<a class="btn btn-danger" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
				Logout
				</a>
				<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
				{{ csrf_field() }}
				</form>
                <h2>Laravel CRUD Application</h2>
            </div>
            <div class="pull-right">
             <a class="btn btn-success" href="{{ route('siswa_nilai.create') }}"> Create New Data</a>
            </div>
             
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>KD_PROP</th> 
			<th>KD_RAYO</th>
			<th>KD_SR</th>
			<th>KD_SEK</th>
			<th>NOPES</th>
			<th>NM_PES</th>
			<th>NISN</th>
			<th>SEX</th>
			<th>TMP_LHR</th>
			<th>TGL_LHR</th>
			<th>ALAMAT_1</th>
			<th>IND</th>
			<th>MAT</th>
			<th>IPA</th>
            <th width="280px">Action</th>

        </tr>

        @foreach ($siswa_nilai as $dataSiswa)

        <tr>

            <td>{{ ++$i }}</td>
            <td>{{ $dataSiswa->KD_PROP }}</td>
            <td>{{ $dataSiswa->KD_RAYO }}</td>
            <td>{{ $dataSiswa->KD_SR }}</td>
            <td>{{ $dataSiswa->KD_SEK }}</td>
            <td>{{ $dataSiswa->NOPES }}</td>
            <td>{{ $dataSiswa->NM_PES }}</td>
            <td>{{ $dataSiswa->NISN }}</td>
            <td>{{ $dataSiswa->SEX }}</td>
            <td>{{ $dataSiswa->TMP_LHR }}</td>
            <td>{{ $dataSiswa->TGL_LHR }}</td>
            <td>{{ $dataSiswa->ALAMAT_1 }}</td>
            <td>{{ $dataSiswa->IND }}</td>
            <td>{{ $dataSiswa->MAT }}</td>
            <td>{{ $dataSiswa->IPA }}</td>
                                 
            <td>

                <form action="{{ route('siswa_nilai.destroy',$dataSiswa->id) }}" method="POST">

   

                    <a class="btn btn-info" href="{{ route('siswa_nilai.show',$dataSiswa->id) }}">Show</a>

    

                    <a class="btn btn-primary" href="{{ route('siswa_nilai.edit',$dataSiswa->id) }}">Edit</a>

   

                    {{ csrf_field() }}

                    {{ method_field('DELETE') }}

      

                    <button type="submit" class="btn btn-danger">Delete</button>

                </form>
            </td>
        </tr>

        @endforeach

    </table>

  

    {!! $siswa_nilai->links() !!}

      

@endsection

resources/views/siswa_nilai/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel CRUD Application</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>

<body>
	
    @if(Auth::check())
<div class="container">
    @yield('content')
</div>
	@endif
	
	@if(Auth::guest())
   <a href="/login" class="btn btn-info"> Silahkan login terlebih dahulu >></a>
    @endif
</body>
</html>

resources/views/siswa_nilai/show.blade.php
@extends('siswa_nilai.layout')


@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2> Show Data</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('siswa_nilai.index') }}"> Back</a>

            </div>

        </div>

    </div>
   

    <div class="row">
		
	
	
	  <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Kode Propinsi:</strong>
            {{ $dataSiswa->KD_PROP }}
           
         </div>            
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Kode Rayon:</strong>
            {{ $dataSiswa->KD_RAYO }}
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Kode SR:</strong>            
            {{ $dataSiswa->KD_SR }}            
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Kode Sekolah:</strong>            
            {{ $dataSiswa->KD_SEK }}           
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Nomor Peserta:</strong>            
            {{ $dataSiswa->NOPES }}            
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Nama Peserta:</strong>            
            {{ $dataSiswa->NM_PES }}            
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>NISN:</strong>            
            {{ $dataSiswa->NISN }}            
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Jenis Kelamin:</strong>            
            {{ $dataSiswa->SEX }}            
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Tempat Kelahiran:</strong>            
            {{ $dataSiswa->TMP_LHR }}            
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Tanggal Lahir:</strong>            
            {{ $dataSiswa->TGL_LHR }}            
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>Alamat:</strong>            
            {{ $dataSiswa->ALAMAT_1 }}            
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>IND:</strong>            
            {{ $dataSiswa->IND }}            
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>MAT:</strong>            
            {{ $dataSiswa->MAT }}            
         </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
         <div class="form-group">
            <strong>IPA:</strong>            
            {{ $dataSiswa->IPA }}            
         </div>
      </div>
	
    </div>

@endsection